# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
   - hostPath: ./volumes
     containerPath: /opt/volumes
  extraPortMappings:
    - containerPort: 30443
      hostPort: 30443
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 80
      hostPort: 80
      listenAddress: "0.0.0.0"
      protocol: tcp
- role: worker
  extraMounts:
   - hostPath: ./volumes
     containerPath: /opt/volumes
  extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 8080
      hostPort: 8080
      listenAddress: "0.0.0.0"
      protocol: tcp
     
